---
- name: Activate virtual env, install and repair npm
  shell: 
    chdir: '{{ galaxy_install_dir }}'
    cmd: . venv/bin/activate; cd '{{ galaxy_server_dir }}/lib/galaxy/web/proxy/js'; npm install; npm audit fix
  become_user: root
  become_method: sudo

- name: Copy ini.sample to ini
  copy:
    src: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/{{ item }}.ini.sample'
    dest: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/{{ item }}.ini'
    remote_src: true
  with_items:
    - jupyter
    - rstudio

- name: Copy allowed_images.yml.sample to allowed_images.yml
  copy:
    src: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/allowed_images.yml.sample'
    dest: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/allowed_images.yml'
    remote_src: true
  with_items:
    - jupyter
    - rstudio

- name: Interactive environment configuration
  ini_file:
    path: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item.name }}/config/{{ item.name }}.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value}}'
  with_items:
    - { name: jupyter , section: "docker", option: "use_volumes", value: "False" }
    - { name: rstudio , section: "docker", option: "use_volumes", value: "False" }
    - { name: jupyter , section: "docker", option: "wx_tempdir", value: "True"  }
    - { name: rstudio , section: "docker", option: "wx_tempdir", value: "True"  }

# Current Jupyter image is not working by default.
# An issue has been opened.
# https://github.com/bgruening/docker-jupyter-notebook/issues/50
- name: New allowed image file jupyter
  copy:
    src: jupyter_allowed_images.yml
    dest: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/jupyter/config/allowed_images.yml'

- name: Ensure docker.py is installed
  pip:
    name: docker-py
    state: present
  become_user: root
  become_method: sudo

- name: Pull selected docker images
  docker_image:
    name: '{{ item }}' 
    source: pull
  with_items:
    - quay.io/laniakeacloud/docker-jupyter-notebook:v1.0.0-beta1
    - quay.io/erasche/docker-rstudio-notebook:19.05

- name: restart galaxy
  service:
    name: galaxy
    state: restarted
  become_user: root
  become_method: sudo
