---
- name: Activate virtual env, install and repair npm
  become: true
  become_user: root
  shell: 
    chdir: '{{ galaxy_install_dir }}'
    cmd: . venv/bin/activate; cd '{{ galaxy_server_dir }}/lib/galaxy/web/proxy/js'; npm install; npm audit fix

- name: copy ini.sample to ini
  become: true 
  become_user: root
  copy:
    src: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/{{ item }}.ini.sample'
    dest: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/{{ item }}.ini'
    remote_src: true
  with_items:
    - jupyter
    - rstudio

- name: .ini.sample to .ini
  become: true 
  become_user: root
  copy:
    src: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/allowed_images.yml.sample'
    dest: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}/config/allowed_images.yml'
    remote_src: true
  with_items:
    - jupyter
    - rstudio

- name: interactive configuration
  lineinfile:
    path: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item.name }}/config/{{ item.name }}.ini'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { name: jupyter , regexp: "#use_volumes = True" , line: "use_volumes = False" }
    - { name: rstudio , regexp: "#use_volumes = True" , line: "use_volumes = False" }
    - { name: jupyter , regexp: "#wx_tempdir = False" , line: "wx_tempdir = True"  }
    - { name: rstudio , regexp: "#wx_tempdir = False" , line: "wx_tempdir = True"  }

- name: new allowed image file jupyter
  copy:
    src: jupyter_allowed_images.yml
    dest: '{{ galaxy_server_dir }}/config/plugins/interactive_environments/jupyter/config/allowed_images.yml'

#- name: install docker.py
#  pip:
#    name: docker-py
#    state: present

- name: pull selected docker images
  docker_image:
    name: '{{ item }}' 
    source: pull
  with_items:
    - quay.io/laniakeacloud/docker-jupyter-notebook:v1.0.0-beta1
    - quay.io/erasche/docker-rstudio-notebook:19.05

- name: restart galaxy
  service:
    name: galaxy
    state: restarted
